title: yuribreion
email: yuribreion
description: > # this means to ignore newlines until "baseurl:"
  Coisas de dev para devs
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: yuribreion
github_username:  yuribreion1

markdown: kramdown

highlighter: rouge

paginate: 15
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
paginate: 5

collections:
  java:
    output: true
    permalink: /java/:path/
  php:
    output: true
    permalink: /php/:path/


